on: push
name: Publish Website

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    strategy:
     matrix:
       node-version: [ 10.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run dist --if-present
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        ftp-server: ftpupload.net
        ftp-username: epiz_25364283
        ftp-password: ${{ secrets.test72_ftp_password }}
        local-dir: dist
        remote-dir: htdocs
      env:
        ARGS: --delete --exclude README.md --exclude .git --exclude .github 

