name: DataUploader

on:
  schedule:
    - cron: '25 18 * * *'

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]
    steps:
    - name: CreateDataDir
      run: mkdir dist/data
    - name: UploadData
      run: wget -O dist/data/dpc-covid19-ita-andamento-nazionale.json https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-json/dpc-covid19-ita-andamento-nazionale.json
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftpupload.net
        FTP_USERNAME: epiz_25412810
        FTP_PASSWORD: ${{ secrets.worlddata_ftp_password }}
        LOCAL_DIR: dist
        REMOTE_DIR: htdocs
