on:
   schedule:
     - cron: '30 16 * * *'
name: DataUploader

jobs:
  linux:
    name: Linux build on node 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10.x]
    steps:
    - name: CreateDataDir
      run: mkdir -p dist/data
    - name: UploadNationalData
      run: wget -O dist/data/dpc-covid19-ita-andamento-nazionale.csv https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
    - name: UploadRegionalData
      run: wget -O dist/data/dpc-covid19-ita-regioni-latest.csv https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv
    - name: List data Dir
      run: ls -la dist/data
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftpupload.net
        FTP_USERNAME: epiz_25412810
        FTP_PASSWORD: ${{ secrets.worlddata_ftp_password }}
        LOCAL_DIR: dist
        REMOTE_DIR: geokei.com/htdocs
